services:
  server:
    platform: linux/arm64
    restart: unless-stopped
    image: cascarita-server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    command: /bin/sh -c "npm run migrate && npm run server"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server:/app
    depends_on:
      db:
        condition: service_healthy

  client:
    platform: linux/arm64
    restart: unless-stopped
    image: cascarita-client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
    command: pnpm run dev
    volumes:
      - ./client/src:/app/src
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: cascarita
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
