version: "3.8"

services:
  server:
    platform: linux/arm64
    restart: unless-stopped
    image: cascarita-server
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/app/server
      - ./dist:/app/dist
    # NOTE, if you change the .env SERVER_PORT, please update here to match
    # Please update in the corresponding Dockerfile as well
    ports:
      - "3001:3001"
    command: npm run server

  # NOTE: server will out monolith app, client will be activated once
  # reverse proxy solution has been implemented

  # client:
  #   platform: linux/arm64
  #   restart: unless-stopped
  #   image: cascarita-client
  #   build:
  #     context: .
  #     dockerfile: client/Dockerfile
  #   # NOTE, if you change the .env CLIENT_PORT, please update here to match
  #   # Please update in the corresponding Dockerfile as well
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app/client
  #     - ./dist:/app/dist
  #   command: npm run client
