version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run server

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run client
