name: 🎯 Main CI
on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEST_DB_NAME: test_suite_db
      TEST_DB_USERNAME: root
      TEST_DB_PASSWORD: root
      TEST_DB_DIALECT: mysql

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Eslint Checks
        run: npm run eslint

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Jest Tests
        run: npm run test

      - name: Webpack Build
        run: npm run build

      - name: Start the app
        run: npm run start > app_output.log 2>&1 &
        env:
          PORT: 3001

      - name: Wait for the app to start
        run: sleep 10

      - name: Display logs
        run: |
          echo "Application logs: $(cat app_output.log)"

      - name: Check if the app is up
        run: curl -I http://127.0.0.1:3001
