name: 🎯 Main CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Run the build-and-test job"
        default: "run"
        required: true
  workflow_call:
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: install dependencies for linting
        run: |
          cd client
          pnpm install
          cd ..

      - name: run linter
        run: make eslint

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Compile assets
        run: make build
