name: 🎯 Main CI
on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Load .env file
        run: |
          set -o allexport
          source <(grep -v '^#' .env | xargs -d '\n')
          set +o allexport

      - name: Debug Environment Variables
        run: |
          echo "TEST_DB_HOST: $TEST_DB_HOST"
          echo "TEST_DB_NAME: $TEST_DB_NAME"
          echo "TEST_DB_PASSWORD: $TEST_DB_PASSWORD"
          echo "TEST_DB_USERNAME: $TEST_DB_USERNAME"
          echo "TEST_DB_DIALECT: $TEST_DB_DIALECT"
          echo "TEST_DB_PORT: $TEST_DB_PORT"
          echo "TEST_DB_LOGGING: $TEST_DB_LOGGING"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Eslint Checks
        run: npm run eslint

      - name: Start MySQL
        run: |
          sudo service mysql start
          export MYSQL_USER="$TEST_DB_USERNAME"
          export MYSQL_PASSWORD="$TEST_DB_PASSWORD"
          export MYSQL_DB="$TEST_DB_NAME"
          mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DB;"

      - name: Jest Tests
        run: npm run test

      - name: Webpack Build
        run: npm run build

      - name: Start the app
        run: npm run start > app_output.log 2>&1 &
        env:
          PORT: 3001

      - name: Wait for the app to start
        run: sleep 10

      - name: Display logs
        run: |
          echo "Application logs: $(cat app_output.log)"

      - name: Check if the app is up
        run: curl -I http://127.0.0.1:3001
